
services:
  jellyfin:
    security_opt: # enables full access to /sys and /proc, still far better than privileged: true
      - systempaths=unconfined
      - apparmor=unconfined
    group_add:
      - "109" # Change this to match your "render" host group id. Use command: getent group render | cut -d: -f3
      - "44" # Change this to match your "video" host group id. Use command: getent group video | cut -d: -f3
    volumes:
      - ./ANY_YOU_NEED:/ANY_YOU_NEED
    # privileged: true
    network_mode: host
    dns:
      - 9.9.9.9
      - 1.1.1.1
    # ports:
    #   - 8096:8096
    environment:
      JELLYFIN_PublishedServerUrl: http://example.com
      ROC_ENABLE_PRE_VEGA: 1
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render node
      - /dev/dma_heap:/dev/dma_heap
      - /dev/kfd:/dev/kfd # Remove this device if you don't use the OpenCL tone-mapping
      # - /dev/mali0:/dev/mali0 # Only for Pi/Arm devices
      # - /dev/rga:/dev/rga # Only for Pi/Arm devices
      # - /dev/mpp_service:/dev/mpp_service # Only for Pi/Arm devices
  # jellystat-db:
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: mypassword
  # jellystat:
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: mypassword
  #     POSTGRES_IP: jellystat-db
  #     POSTGRES_PORT: 5432
  #     JWT_SECRET: 'my-secret-jwt-key'