version: '3'
services:
  jellyfin:
    container_name: jellyfin
    image: "jellyfin/jellyfin:latest"
    user: 1000:1000
    environment:
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
      # ROC_ENABLE_PRE_VEGA: 1
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    # privileged: true
    # network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
