version: '3'
services:
  jellyfin:
    container_name: jellyfin
    image: "jellyfin/jellyfin:latest"
    # user: uid:gid
    environment:
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
      # JELLYFIN_PublishedServerUrl: http://example.com
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    # privileged: true
    # network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1

  nginx:
    container_name: jellyfin-proxy
    image: nginx
    volumes:
    # - ./templates:/etc/nginx/templates
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=jellyfin.example.org
    - NGINX_PORT=80