version: '3'
services:
  jellyfin:
    container_name: jellyfin
    image: "jellyfin/jellyfin:latest"
    user: 1000:1000
    environment:
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  jellystat-db:
    image: postgres:15.2
    environment:
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
    - ./postgres-data:/var/lib/postgresql/data # Mounting the volume
  jellystat:
    image: cyfershepard/jellystat:latest
    environment:
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    ports:
      - "3000:3000" #Server Port
    volumes:
      - ./backup-data:/app/backend/backup-data # Mounting the volume
    depends_on:
      - jellystat-db

volumes:
  config:
  cache:
  media:
  data:
  backup-data: