version: '3'
services:
  jellyfin:
    container_name: jellyfin
    image: "jellyfin/jellyfin:latest"
    user: 1000:1000
    environment:
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
